"use server";

import { createClient } from "@/utils/supabase/server";

export interface GenerateInvitationResult {
    success: boolean;
    wardrobeId?: string;
    uploadToken?: string;
    error?: string;
}

/**
 * Generate a wardrobe invitation link.
 * Instead of creating a ghost profile, we now create a wardrobe with an upload token.
 * The guest can upload items directly via the token without needing an account.
 */
export async function generateInvitation(
    clientName: string,
    email: string = "",
    note: string = ""
): Promise<GenerateInvitationResult> {
    const supabase = await createClient();

    // 1. Check if Admin
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { success: false, error: "Unauthorized" };

    const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
    if (profile?.role !== 'admin') return { success: false, error: "Unauthorized" };

    try {
        // 2. Create Wardrobe with Upload Token
        const { data: wardrobe, error } = await supabase
            .from('wardrobes')
            .insert({
                title: `${clientName}'s Wardrobe`,
                owner_id: null, // Admin-managed, no owner yet
                // upload_token is auto-generated by default
            })
            .select('id, upload_token')
            .single();

        if (error) {
            console.error("DB Error:", error);
            throw new Error(error.message);
        }

        // Note: We store client name/email in wardrobe metadata if needed in future
        // For now, the wardrobe title serves as the identifier

        return {
            success: true,
            wardrobeId: wardrobe.id,
            uploadToken: wardrobe.upload_token
        };

    } catch (err: unknown) {
        console.error("Invitation Error:", err);
        return { success: false, error: (err as Error).message };
    }
}

/**
 * Claim a wardrobe for a user (when they sign up after using an upload link)
 */
export async function claimWardrobe(
    wardrobeId: string,
    userId: string
): Promise<{ success: boolean; error?: string }> {
    const supabase = await createClient();

    const { error } = await supabase
        .from('wardrobes')
        .update({ owner_id: userId })
        .eq('id', wardrobeId)
        .is('owner_id', null); // Only claim if currently unclaimed

    if (error) {
        console.error("Claim Wardrobe Error:", error);
        return { success: false, error: error.message };
    }

    return { success: true };
}
